apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: app4
  annotations:
    haproxy.org/path-rewrite: |
      ^/api/(.*) /\1

spec:
  ingressClassName: nginx
  rules:
    - host: app4.local
      http:
        paths:
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
