apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: eks-4
spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: docker.io/achalpadol/react-rust-post:v1 
          imagePullPolicy: Always

          ports:
            - containerPort: 80
